using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using TAP.Parts;
using UnityEditor;
using UnityEditor.Formats.Fbx.Exporter;
using UnityEngine;

namespace TAP.EditorTools
{
    /// <summary>
    /// Exports the generated part models for editing in Blender or another 3D tool (Docs/PART_MODELS.md): FBX with the
    /// named hierarchy, pivots and material names (the file to edit), OBJ + MTL (one file per part, for tools that
    /// prefer it) and PARTS.md, which lists each part's size, attach nodes and the transforms the game animates.
    /// A model saved as Assets/TAP/Resources/PartModels/&lt;part id&gt;.fbx replaces the generated one in the game.
    /// </summary>
    public static class PartModelExporter
    {
        public const string ExportDir = "Art/PartModels/Export";
        public const string CustomDir = "Assets/TAP/Resources/PartModels";

        private static string ProjectRoot => Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
        private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

        [MenuItem("TAP/Part Models/Export All (FBX + OBJ)")]
        public static void ExportAllMenu()
        {
            string r = ExportAll();
            EditorUtility.DisplayDialog("Part models", r + "\n\nEdit a model, then save it as " + CustomDir + "/<part id>.fbx to use it in the game (Docs/PART_MODELS.md).", "OK");
            EditorUtility.RevealInFinder(Path.Combine(ProjectRoot, ExportDir, "PARTS.md"));
        }

        [MenuItem("TAP/Part Models/Open Hand-made Models Folder")]
        public static void OpenCustomFolder()
        {
            Directory.CreateDirectory(Path.Combine(ProjectRoot, CustomDir));
            EditorUtility.RevealInFinder(Path.Combine(ProjectRoot, CustomDir));
        }

        /// <summary>Writes every part's generated model to Art/PartModels/Export and returns a one-line summary.</summary>
        public static string ExportAll()
        {
            var db = PartDatabase.LoadFromResources();
            string dir = Path.Combine(ProjectRoot, ExportDir);
            Directory.CreateDirectory(Path.Combine(dir, "obj"));
            var options = new ExportModelOptions
            {
                ExportFormat = ExportFormat.Binary,
                ModelAnimIncludeOption = Include.Model,
                ObjectPosition = ObjectPosition.Reset,
                UseMayaCompatibleNames = false,
                ExportUnrendered = true,
            };
            var doc = new StringBuilder();
            doc.AppendLine("# Part models — reference sheet");
            doc.AppendLine();
            doc.AppendLine("Generated by *TAP → Part Models → Export All*. Units are metres, +Y is up (the top of the part), the part");
            doc.AppendLine("origin is at 0,0,0. Keep the names in **Animated** (with their pivots) and the attach nodes where they are; anchors");
            doc.AppendLine("are placed from the part data. Workflow: [Docs/PART_MODELS.md](../../../Docs/PART_MODELS.md).");
            doc.AppendLine();
            int fbx = 0, obj = 0;
            foreach (var def in db.Parts)
            {
                var go = PartModelFactory.Build(def, 0, generated: true);
                try
                {
                    foreach (var c in go.GetComponentsInChildren<Collider>()) Object.DestroyImmediate(c);
                    if (ModelExporter.ExportObject(Path.Combine(dir, def.id + ".fbx"), go, options) != null) fbx++;
                    File.WriteAllText(Path.Combine(dir, "obj", def.id + ".obj"), Obj(go, def));
                    obj++;
                    Describe(doc, def, go);
                }
                finally { Object.DestroyImmediate(go); }
            }
            File.WriteAllText(Path.Combine(dir, "obj", "part_materials.mtl"), Mtl());
            File.WriteAllText(Path.Combine(dir, "PARTS.md"), doc.ToString());
            string msg = $"Exported {fbx} FBX and {obj} OBJ part models to {dir}";
            Debug.Log("[PartModels] " + msg);
            return msg;
        }

        // ------------------------------------------------------------------ reference sheet

        private static void Describe(StringBuilder doc, PartDefinition def, GameObject go)
        {
            var model = go.transform.Find("Model");
            doc.AppendLine($"## `{def.id}` — {def.title}");
            doc.AppendLine();
            doc.AppendLine($"* Category {def.category}, generated shape `{def.model?.type ?? "tank"}`, bounding cylinder {F(def.diameter)} m wide × {F(def.height)} m tall");
            var mats = go.GetComponentsInChildren<Renderer>().SelectMany(r => r.sharedMaterials).Where(m => m != null).Select(m => m.name).Distinct();
            doc.AppendLine($"* Materials: {string.Join(", ", mats.Select(m => $"`{m}`"))}");
            var animated = new List<string>();
            if (model != null)
                foreach (var t in model.GetComponentsInChildren<Transform>(true))
                    if (t != model && !IsAnchor(t.name)) animated.Add($"`{PathOf(t, model)}` at {V(go.transform.InverseTransformPoint(t.position))}");
            if (animated.Count > 0) doc.AppendLine($"* Animated (keep names and pivots, children of `Model`): {string.Join("; ", animated)}");
            var anchors = go.GetComponentsInChildren<Transform>(true).Where(t => IsAnchor(t.name))
                .Select(t => $"`{t.name}` at {V(go.transform.InverseTransformPoint(t.position))}").ToList();
            if (anchors.Count > 0) doc.AppendLine($"* Anchors (from the part data): {string.Join("; ", anchors)}");
            if (def.nodes.Count > 0)
                doc.AppendLine($"* Attach nodes: {string.Join("; ", def.nodes.Select(n => $"`{n.id}` at {V(n.Position)} facing {V(n.Direction)}"))}");
            if (def.surfaceAttach.allowed) doc.AppendLine("* Attaches to the surface of other parts by its back (−Z side)");
            doc.AppendLine();
        }

        private static bool IsAnchor(string name) =>
            name == "Nozzle" || name == "CanopyAnchor" || name == "Hatch" || name.StartsWith("RcsNozzle");

        private static string PathOf(Transform t, Transform root)
        {
            var names = new List<string>();
            for (var x = t; x != null && x != root; x = x.parent) names.Insert(0, x.name);
            return string.Join("/", names);
        }

        private static string F(float v) => v.ToString("0.###", Inv);
        private static string V(Vector3 v) => $"({F(v.x)}, {F(v.y)}, {F(v.z)})";

        // ------------------------------------------------------------------ OBJ

        /// <summary>
        /// One OBJ object per mesh, named by its path under the part. OBJ is right-handed, Unity left-handed: X is
        /// mirrored and the triangle winding reversed, so the part looks the same in both.
        /// </summary>
        private static string Obj(GameObject root, PartDefinition def)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"# The Astraea Program part model {def.id} ({def.title}), generated. Metres, +Y up.");
            sb.AppendLine("mtllib part_materials.mtl");
            int vBase = 1;
            foreach (var mf in root.GetComponentsInChildren<MeshFilter>())
            {
                var mesh = mf.sharedMesh;
                var mr = mf.GetComponent<MeshRenderer>();
                if (mesh == null || mr == null) continue;
                var toRoot = root.transform.worldToLocalMatrix * mf.transform.localToWorldMatrix;
                sb.AppendLine("o " + (mf.transform == root.transform ? def.id : PathOf(mf.transform, root.transform)));
                var verts = mesh.vertices;
                var normals = mesh.normals;
                var uvs = mesh.uv;
                bool hasN = normals.Length == verts.Length, hasUv = uvs.Length == verts.Length;
                foreach (var v in verts)
                {
                    var p = toRoot.MultiplyPoint3x4(v);
                    sb.Append("v ").Append((-p.x).ToString("0.#####", Inv)).Append(' ').Append(p.y.ToString("0.#####", Inv)).Append(' ').AppendLine(p.z.ToString("0.#####", Inv));
                }
                if (hasN)
                    foreach (var n in normals)
                    {
                        var q = toRoot.MultiplyVector(n).normalized;
                        sb.Append("vn ").Append((-q.x).ToString("0.####", Inv)).Append(' ').Append(q.y.ToString("0.####", Inv)).Append(' ').AppendLine(q.z.ToString("0.####", Inv));
                    }
                if (hasUv)
                    foreach (var uv in uvs)
                        sb.Append("vt ").Append(uv.x.ToString("0.#####", Inv)).Append(' ').AppendLine(uv.y.ToString("0.#####", Inv));
                var mats = mr.sharedMaterials;
                for (int s = 0; s < mesh.subMeshCount; s++)
                {
                    sb.AppendLine("usemtl " + (s < mats.Length && mats[s] != null ? mats[s].name : "Part_White"));
                    var tris = mesh.GetTriangles(s);
                    for (int i = 0; i + 2 < tris.Length; i += 3)
                    {
                        int a = tris[i] + vBase, b = tris[i + 2] + vBase, c = tris[i + 1] + vBase;
                        sb.AppendLine(hasUv && hasN ? $"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}"
                                    : hasN ? $"f {a}//{a} {b}//{b} {c}//{c}"
                                    : $"f {a} {b} {c}");
                    }
                }
                vBase += verts.Length;
            }
            return sb.ToString();
        }

        /// <summary>The shared part materials as MTL (colour, and the PBR extension's metallic/roughness).</summary>
        private static string Mtl()
        {
            var sb = new StringBuilder("# The Astraea Program shared part materials\n");
            foreach (var kv in PartMaterials.Palette)
            {
                var (c, metallic, smoothness) = kv.Value;
                sb.AppendLine();
                sb.AppendLine("newmtl Part_" + kv.Key);
                sb.AppendLine($"Kd {c.r.ToString("0.###", Inv)} {c.g.ToString("0.###", Inv)} {c.b.ToString("0.###", Inv)}");
                sb.AppendLine("Ks 0.04 0.04 0.04");
                sb.AppendLine("Ns " + (smoothness * 900 + 10).ToString("0", Inv));
                sb.AppendLine("Pm " + metallic.ToString("0.##", Inv));
                sb.AppendLine("Pr " + (1 - smoothness).ToString("0.##", Inv));
                sb.AppendLine("illum 2");
            }
            sb.AppendLine();
            sb.AppendLine("newmtl FlagCloth");
            sb.AppendLine("Kd 1 1 1");
            sb.AppendLine("illum 1");
            return sb.ToString();
        }
    }

    /// <summary>Import settings for hand-made part models: meshes and materials only (no colliders, cameras or animation).</summary>
    public sealed class PartModelImportSettings : AssetPostprocessor
    {
        private void OnPreprocessModel()
        {
            if (!assetPath.Replace('\\', '/').StartsWith(PartModelExporter.CustomDir + "/")) return;
            var mi = (ModelImporter)assetImporter;
            if (!mi.importSettingsMissing) return; // first import only: later changes in the inspector stay
            mi.importAnimation = false;
            mi.importCameras = false;
            mi.importLights = false;
            mi.addCollider = false;
            mi.isReadable = false;
            mi.useFileScale = true;
            mi.globalScale = 1f;
            mi.preserveHierarchy = true;
        }
    }
}
