using System.Collections.Generic;
using UnityEngine;

namespace TAP.Parts
{
    public enum MatSlot
    {
        White = 0, Dark = 1, Orange = 2, Metal = 3, MetalDark = 4, Gold = 5, Glass = 6, Shield = 7,
        Yellow = 8, Red = 9, Black = 10, Suit = 11, Visor = 12, Canopy = 13, Concrete = 14, Blue = 15, Grey = 16,
    }

    /// <summary>
    /// Shared URP materials for all part/prop models. Loaded from Resources/Materials (generated by the
    /// editor asset builder) with a runtime fallback that creates URP/Lit materials directly.
    /// </summary>
    public static class PartMaterials
    {
        private static Material[] _mats;
        private static Material _canopy, _exhaust, _plasma, _flagCloth;

        public static readonly Dictionary<MatSlot, (Color color, float metallic, float smoothness)> Palette =
            new Dictionary<MatSlot, (Color, float, float)>
            {
                { MatSlot.White, (new Color(0.88f, 0.89f, 0.9f), 0f, 0.45f) },
                { MatSlot.Dark, (new Color(0.13f, 0.14f, 0.16f), 0.1f, 0.38f) },
                { MatSlot.Orange, (new Color(0.86f, 0.42f, 0.14f), 0f, 0.35f) },
                { MatSlot.Metal, (new Color(0.66f, 0.67f, 0.7f), 0.85f, 0.55f) },
                { MatSlot.MetalDark, (new Color(0.24f, 0.24f, 0.26f), 0.8f, 0.45f) },
                { MatSlot.Gold, (new Color(0.93f, 0.7f, 0.28f), 1f, 0.62f) },
                { MatSlot.Glass, (new Color(0.08f, 0.12f, 0.18f), 0.2f, 0.95f) },
                { MatSlot.Shield, (new Color(0.3f, 0.21f, 0.15f), 0f, 0.12f) },
                { MatSlot.Yellow, (new Color(0.95f, 0.78f, 0.12f), 0f, 0.4f) },
                { MatSlot.Red, (new Color(0.72f, 0.1f, 0.08f), 0f, 0.4f) },
                { MatSlot.Black, (new Color(0.03f, 0.03f, 0.035f), 0f, 0.2f) },
                { MatSlot.Suit, (new Color(0.92f, 0.92f, 0.9f), 0f, 0.3f) },
                { MatSlot.Visor, (new Color(0.75f, 0.55f, 0.2f), 1f, 0.92f) },
                { MatSlot.Canopy, (new Color(1f, 1f, 1f), 0f, 0.25f) },
                { MatSlot.Concrete, (new Color(0.52f, 0.52f, 0.5f), 0f, 0.15f) },
                { MatSlot.Blue, (new Color(0.12f, 0.3f, 0.7f), 0f, 0.4f) },
                { MatSlot.Grey, (new Color(0.45f, 0.46f, 0.48f), 0.2f, 0.35f) },
            };

        public static Material Get(MatSlot slot)
        {
            EnsureLoaded();
            return _mats[(int)slot];
        }

        public static Material[] ForSlots(int[] slots)
        {
            EnsureLoaded();
            var arr = new Material[slots.Length];
            for (int i = 0; i < slots.Length; i++) arr[i] = _mats[slots[i]];
            return arr;
        }

        private static void EnsureLoaded()
        {
            if (_mats != null) return;
            int count = System.Enum.GetValues(typeof(MatSlot)).Length;
            _mats = new Material[count];
            for (int i = 0; i < count; i++)
            {
                var slot = (MatSlot)i;
                var m = Resources.Load<Material>("Materials/Part_" + slot);
                if (m == null) m = CreateLit("Part_" + slot, Palette[slot].color, Palette[slot].metallic, Palette[slot].smoothness, true);
                _mats[i] = m;
            }
        }

        public static Material CreateLit(string name, Color c, float metallic, float smoothness, bool emission)
        {
            var sh = Shader.Find("Universal Render Pipeline/Lit");
            var m = new Material(sh) { name = name };
            m.SetColor("_BaseColor", c);
            m.SetFloat("_Metallic", metallic);
            m.SetFloat("_Smoothness", smoothness);
            if (emission)
            {
                m.EnableKeyword("_EMISSION");
                m.SetColor("_EmissionColor", Color.black);
                m.globalIlluminationFlags = MaterialGlobalIlluminationFlags.None;
            }
            return m;
        }

        public static Material Canopy
        {
            get
            {
                if (_canopy == null)
                {
                    _canopy = Resources.Load<Material>("Materials/Canopy");
                    if (_canopy == null)
                    {
                        _canopy = CreateLit("Canopy", Color.white, 0, 0.2f, false);
                        _canopy.SetFloat("_Cull", 0f); // double sided
                    }
                }
                return _canopy;
            }
        }

        /// <summary>Additive material used by exhaust / RCS / plasma particle effects.</summary>
        public static Material Exhaust
        {
            get
            {
                if (_exhaust == null)
                {
                    _exhaust = Resources.Load<Material>("Materials/ExhaustAdditive");
                    if (_exhaust == null)
                    {
                        var sh = Shader.Find("Universal Render Pipeline/Particles/Unlit");
                        _exhaust = new Material(sh) { name = "ExhaustAdditive" };
                        _exhaust.SetFloat("_Surface", 1);
                        _exhaust.SetFloat("_Blend", 2); // additive
                    }
                }
                return _exhaust;
            }
        }

        public static Material FlagCloth
        {
            get
            {
                if (_flagCloth == null)
                {
                    _flagCloth = Resources.Load<Material>("Materials/FlagCloth");
                    if (_flagCloth == null) _flagCloth = CreateLit("FlagCloth", Color.white, 0, 0.2f, false);
                }
                return _flagCloth;
            }
        }
    }
}
